run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - nilerr
    - sqlclosecheck
    - rowserrcheck
    - gofmt
    - goimports
    - revive
    - unconvert
    - unparam
    - unused
    - ineffassign
    - misspell
    - prealloc
    - gocritic
    - gosec
    - gocognit
    - cyclop
    - goconst
    - errorlint

linters-settings:
  gocognit:
    min-complexity: 20

  cyclop:
    max-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - unnecessaryBlock

  revive:
    rules:
      - name: exported
        disabled: true
      - name: unused-parameter
        disabled: true

  gosec:
    excludes:
      - G115

  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

  errorlint:
    errorf: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gocognit
        - cyclop
        - errcheck
        - gosec
        - unparam
        - gocritic

    - path: ^gen/
      linters:
        - revive
        - gocritic
        - gosec
        - errcheck
        - unused
        - unparam
        - stylecheck
        - goconst
        - gofmt
        - goimports

    - path: cmd/.*/main\.go
      linters:
        - gosec